apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dkrf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dkrf
    app.kubernetes.io/part-of: ci1t-830-0077-app
  name: devfile-sample-dkrf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dkrf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dkrf
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0077-tenant/ci1t-830-0077-app/devfile-sample-dkrf@sha256:f834be9debed5accc9bd3ecbf44d0d48a8a3f6dca8f1c95c1a2ffe41b48f1175
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
